"""add sync runs and github events tables

Revision ID: 75e2a6eaa9fe
Revises: fe79b76ace33
Create Date: 2026-02-20 09:46:22.396864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e2a6eaa9fe'
down_revision: Union[str, Sequence[str], None] = 'fe79b76ace33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('github_event_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=True),
    sa.Column('event_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['github_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_event_id')
    )
    op.create_index(op.f('ix_github_events_id'), 'github_events', ['id'], unique=False)
    op.create_index(op.f('ix_github_events_profile_id'), 'github_events', ['profile_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['github_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_runs_profile_id'), 'sync_runs', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_runs_profile_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_github_events_profile_id'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_id'), table_name='github_events')
    op.drop_table('github_events')
    # ### end Alembic commands ###
