"""replace users with github profile tables

Revision ID: fe79b76ace33
Revises: dc9602c31d6c
Create Date: 2026-02-20 09:37:40.311720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe79b76ace33'
down_revision: Union[str, Sequence[str], None] = 'dc9602c31d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_github_profiles_id'), 'github_profiles', ['id'], unique=False)
    op.create_table('heatmap_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['github_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'day', name='uq_profile_day')
    )
    op.create_index(op.f('ix_heatmap_days_id'), 'heatmap_days', ['id'], unique=False)
    op.create_index(op.f('ix_heatmap_days_profile_id'), 'heatmap_days', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_heatmap_days_profile_id'), table_name='heatmap_days')
    op.drop_index(op.f('ix_heatmap_days_id'), table_name='heatmap_days')
    op.drop_table('heatmap_days')
    op.drop_index(op.f('ix_github_profiles_id'), table_name='github_profiles')
    op.drop_table('github_profiles')
    # ### end Alembic commands ###
